# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4                # 升级至 v4，替换 v3 :contentReference[oaicite:1]{index=1}
      - name: Setup Pages environment
        uses: actions/configure-pages@v5         # 升级至 v5，替换 v3 :contentReference[oaicite:2]{index=2}
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3   # 升级至 v3，替换 v2 :contentReference[oaicite:3]{index=3}
        with:
          path: '.'                              # 上传整个仓库作为静态内容
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4            # 升级至 v4，替换 v2 :contentReference[oaicite:4]{index=4}
